In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.2'

In [3]:
!ls ../data

car_fuel_efficiency_2026.csv         plans
car_fuel_efficiency_2026_report.json syntheticgen.log

In [4]:
path = "../data"

In [5]:
df = pd.read_csv(f"{path}/car_fuel_efficiency_2026.csv")

In [6]:
display(df.info())
display(df.head(5))
display(df.isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB

None

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [7]:
for col in df.columns:
    print(col)
    print(df[col].unique()[:10])
    print()

model_year
[2006 2008 1996 1989 1994 2007 1992 2005 1997 2004]

origin
['Europe' 'Asia' 'USA']

fuel_type
['Gasoline' 'Diesel' 'Hybrid']

drivetrain
['Front-wheel drive' 'Rear-wheel drive' 'All-wheel drive']

num_doors
[4 5 3 2]

engine_displacement
[2180 2390 2320 2130 2580 2290 2270 2370 2330 2410]

num_cylinders
[6 7 5 8 4]

horsepower
[243. 272. 267. 258. 304. 266. 250. 279. 251. 280.]

vehicle_weight
[3870 4210 4240 4490 4510 4260 4310 4090 4230 4620]

acceleration
[ nan 17.3 18.7 17.5 18.8 21.7 17.4 19.5 17.7 16.7]

fuel_efficiency_mpg
[31.9 31.3 27.5 28.5 31.  31.2 26.8 30.2 30.9 31.4]

In [8]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [9]:
df[df['origin']=='Asia'].max()

model_year                         2024
origin                             Asia
fuel_type                        Hybrid
drivetrain             Rear-wheel drive
num_doors                             5
engine_displacement                3020
num_cylinders                         8
horsepower                        334.0
vehicle_weight                     5280
acceleration                       23.8
fuel_efficiency_mpg                41.2
dtype: object

In [10]:
horse_power_median = df['horsepower'].median()
most_frequent_value = df['horsepower'].mode(dropna= True)[0]
df['horsepower_new'] = df['horsepower'].fillna(most_frequent_value)
display(horse_power_median)
display(most_frequent_value)
display(df['horsepower'].describe())
display(df['horsepower_new'].describe())

np.float64(254.0)

np.float64(252.0)

count    9123.000000
mean      254.446016
std        22.844613
min       171.000000
25%       239.000000
50%       254.000000
75%       270.000000
max       334.000000
Name: horsepower, dtype: float64

count    10000.000000
mean       254.231500
std         21.830757
min        171.000000
25%        241.000000
50%        252.000000
75%        268.000000
max        334.000000
Name: horsepower_new, dtype: float64

In [14]:
car_asia = df[df['origin'] == 'Asia']
car_asia = car_asia[['vehicle_weight','model_year']]
car_asia_top_7 = car_asia.head(7).to_numpy()

X = car_asia_top_7
XTX = X.T @ X
XTX_invert = np.linalg.inv(XTX)
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
w = XTX_invert @ X.T @ y
display(np.sum(w))

np.float64(0.36919696904925203)